# Generated by Django 5.2.9 on 2025-12-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='drinks/thumbs/'),
        ),
    ]
